server:
  port: 8080
spring:
  application:
    name: auth
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  refresh:
    key: ${JWT_REFRESH_KEY}